import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from "react";
import Navbar from "./components/Navbar"
import Sidebar from "./components/Sidebar"
import AuthGuard from "./components/AuthGuard";

export const metadata: Metadata = {
  title: "Ecommerce demo",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children : ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {

  return (
    <html lang="en">
      <body className="flex min-h-screen">
        <AuthGuard>
          <Sidebar />
          <div className = "flex-1 flex flex-col">
            <Navbar />
            <main className="p-6"> {children}</main>
          </div>
        </AuthGuard>
      </body>
    </html>
  );
}

export default RootLayout;
