
import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from "react";
import AppShell from "./components/AppShell"
import { CartProvider } from "./context/CartContext";
// import AuthSessionCleaner from "./components/AuthSessionCleaner";


export const metadata: Metadata = {
  title: "Ecommerce demo",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children : ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {

  return (
    <html lang="en">
      <body className="flex min-h-screen">
        {/* <AuthSessionCleaner /> */}
        <CartProvider>
          <AppShell>
            {children}
          </AppShell>
        </CartProvider>
      </body>
    </html>
  );
}

export default RootLayout;
